// ─────────────────────────────────────────────────────────────────────────────
// Carevo Retrieval Layer v1 — metadata filters + hybrid lexical/embedding
// ranking, deterministic and replayable.
//
// Design decisions (V2 architecture §6):
//  • Retrieval NEVER influences routing. It selects patient-facing guidance
//    AFTER the engine has decided; a retrieval miss degrades to templates.
//  • Queries are built from the STRUCTURED feature vector, never raw patient
//    text — prompt injection cannot steer what evidence is shown.
//  • Hybrid ranking = BM25 (lexical) + cosine over FROZEN embeddings + an
//    evidence-authority boost. Both chunk AND query vectors are precomputed
//    offline (scripts/embed-corpus.ts) because the query vocabulary is
//    finite (structured features) — so runtime makes NO model calls and the
//    same features + same KB version always retrieve the same chunks.
//  • The index rebuilds automatically when the corpus overlay revision
//    changes (a promotion by the review workbench).
// ─────────────────────────────────────────────────────────────────────────────

import { readFileSync } from 'fs'
import path from 'path'
import type { ExtractedFeatures, PatientRisk } from '../engine/features'
import type { AgeGroup, ContentType, EvidenceStrength, KnowledgeChunk, RetrievedGuidance } from './types'
import { allChunks, allDocuments, kbVersion, KB_BASE_VERSION } from './corpus'

export { kbVersion }
/** @deprecated use kbVersion() */
export const KB_VERSION = KB_BASE_VERSION

// ── Query construction: structured features → search terms ──────────────────

const SYSTEM_TERMS: Record<string, string[]> = {
  cardiac: ['chest pain', 'pressure', 'heart'],
  respiratory: ['breathing', 'shortness of breath', 'wheezing'],
  neuro: ['headache', 'weakness', 'stroke', 'vision'],
  gi: ['stomach', 'vomiting', 'diarrhea', 'dehydration'],
  msk: ['injury', 'fracture', 'swelling', 'sprain'],
  skin: ['rash', 'wound', 'hives', 'swelling'],
  ent: ['throat', 'ear', 'fever', 'breathing'],
  urinary: ['urination', 'urine', 'dehydration'],
  gyn: ['pregnancy', 'bleeding', 'cramping', 'abdominal pain'],
  mental: ['mental health', 'crisis', 'support'],
  general: ['fever', 'fatigue', 'worsening'],
}

function ageGroupFor(risk: PatientRisk): AgeGroup {
  if (risk.modifiers.includes('age_under_2')) return 'infant'
  if (risk.modifiers.includes('age_over_65')) return 'older_adult'
  return 'adult'
}

function queryTerms(f: ExtractedFeatures, risk: PatientRisk): string[] {
  const terms = [...(SYSTEM_TERMS[f.system] ?? [])]
  for (const flag of f.redFlags) terms.push(...flag.split('_'))
  if (f.highFever) terms.push('fever')
  if (f.possibleFracture) terms.push('fracture', 'injury')
  if (f.openWound) terms.push('wound')
  if (f.worsening) terms.push('worsening')
  if (risk.modifiers.includes('immunocompromised')) terms.push('immunocompromised', 'fever')
  if (risk.modifiers.includes('pregnant')) terms.push('pregnancy')
  if (risk.modifiers.includes('age_under_2')) terms.push('child', 'infant')
  return terms.flatMap(t => t.toLowerCase().split(/\s+/))
}

/** Canonical query key for precomputed query embeddings — finite vocabulary
 *  because queries derive from structured features, not free text. */
export function queryEmbeddingKey(contentType: ContentType, system: string, age: AgeGroup): string {
  return `${contentType}|${system}|${age}`
}

/** Canonical query TEXT for a key — used by embed-corpus.ts so offline
 *  embedding and runtime lookup can never drift apart. */
export function queryEmbeddingText(contentType: ContentType, system: string, age: AgeGroup): string {
  const ct: Record<ContentType, string> = {
    warning_signs: 'warning signs, when to seek emergency care',
    self_care: 'safe self care at home',
    follow_up: 'follow up and return precautions',
    education: 'plain language explanation for patients',
  }
  return `${ct[contentType]} for ${(SYSTEM_TERMS[system] ?? [system]).join(', ')} in ${age === 'all' ? 'any' : age} patients`
}

// ── Frozen embeddings (optional; generated by scripts/embed-corpus.ts) ───────

interface EmbeddingsFile {
  model: string
  generatedAt: string
  kbVersion: string
  /** chunkId@vN → unit-normalized vector */
  chunks: Record<string, number[]>
  /** queryEmbeddingKey → unit-normalized vector */
  queries: Record<string, number[]>
}

const EMBEDDINGS_FILE = path.join(process.cwd(), 'data', 'knowledge', 'embeddings.json')
let embCache: { emb: EmbeddingsFile | null; loadedFor: string } | null = null

function loadEmbeddings(version: string): EmbeddingsFile | null {
  if (embCache && embCache.loadedFor === version) return embCache.emb
  let emb: EmbeddingsFile | null = null
  try {
    const parsed = JSON.parse(readFileSync(EMBEDDINGS_FILE, 'utf8')) as EmbeddingsFile
    if (parsed.chunks && parsed.queries && parsed.model) emb = parsed
  } catch { /* embeddings not generated — BM25-only mode */ }
  embCache = { emb, loadedFor: version }
  return emb
}

function cosine(a: number[], b: number[]): number {
  if (a.length !== b.length) return 0
  let dot = 0
  for (let i = 0; i < a.length; i++) dot += a[i] * b[i]
  return dot   // vectors are stored unit-normalized
}

// ── Lexical index (BM25) — rebuilt per KB version ────────────────────────────

const tokenize = (s: string) => s.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/).filter(w => w.length > 2)

interface Index {
  version: string
  chunks: KnowledgeChunk[]
  tokens: Map<string, string[]>
  docFreq: Map<string, number>
  avgLen: number
  docById: Map<string, { title: string; url: string; org: string }>
}

let indexCache: Index | null = null

function getIndex(): Index {
  const version = kbVersion()
  if (indexCache && indexCache.version === version) return indexCache

  const chunks = allChunks()
  const tokens = new Map<string, string[]>(
    chunks.map(c => [c.id, tokenize(c.topics.join(' ') + ' ' + c.topics.join(' ') + ' ' + c.text)]),  // topics double-weighted
  )
  const docFreq = new Map<string, number>()
  for (const t of tokens.values()) for (const term of new Set(t)) docFreq.set(term, (docFreq.get(term) ?? 0) + 1)
  const avgLen = [...tokens.values()].reduce((a, t) => a + t.length, 0) / Math.max(1, tokens.size)
  const docById = new Map(allDocuments().map(d => [d.docId, { title: d.title, url: d.url, org: d.org }]))

  indexCache = { version, chunks, tokens, docFreq, avgLen, docById }
  return indexCache
}

function bm25(ix: Index, chunkId: string, query: string[]): number {
  const tokens = ix.tokens.get(chunkId)
  if (!tokens) return 0
  const N = ix.chunks.length
  const k1 = 1.4, b = 0.6
  const tf = new Map<string, number>()
  for (const t of tokens) tf.set(t, (tf.get(t) ?? 0) + 1)
  let score = 0
  for (const term of new Set(query)) {
    const f = tf.get(term) ?? 0
    if (!f) continue
    const df = ix.docFreq.get(term) ?? 0
    const idf = Math.log(1 + (N - df + 0.5) / (df + 0.5))
    score += idf * (f * (k1 + 1)) / (f + k1 * (1 - b + b * tokens.length / ix.avgLen))
  }
  return score
}

/** Formal guidelines outrank consensus patient education at equal relevance. */
const AUTHORITY_BOOST: Record<EvidenceStrength, number> = {
  clinical_guideline: 0.10,
  public_health_guidance: 0.05,
  professional_consensus: 0,
}

// ── Public API ───────────────────────────────────────────────────────────────

export interface RetrievalResult {
  guidance: RetrievedGuidance[]
  kbVersion: string
}

/**
 * Retrieve the best guidance chunks for a decided case.
 * Hard filters (contentType, system, ageGroup) → hybrid ranking
 * (BM25 + frozen-embedding cosine when available) → authority boost.
 * Deterministic per KB version + embeddings file.
 */
export function retrieveGuidance(
  contentType: ContentType,
  f: ExtractedFeatures,
  risk: PatientRisk,
  opts: { limit?: number } = {},
): RetrievalResult {
  const limit = opts.limit ?? 2
  const ix = getIndex()
  const age = ageGroupFor(risk)
  const query = queryTerms(f, risk)
  const emb = loadEmbeddings(ix.version)
  const queryVec = emb?.queries[queryEmbeddingKey(contentType, f.system, age)]

  const pool = ix.chunks.filter(c =>
    c.contentType === contentType &&
    c.systems.includes(f.system) &&
    (c.ageGroup === 'all' || c.ageGroup === age ||
      (c.ageGroup === 'child' && age === 'infant') ||
      (c.ageGroup === 'adult' && age === 'older_adult')),
  )
  if (!pool.length) return { guidance: [], kbVersion: ix.version }

  // BM25, normalized within the pool
  const lex = pool.map(c => bm25(ix, c.id, query))
  const maxLex = Math.max(...lex, 1e-9)

  const scored = pool.map((c, i) => {
    const lexNorm = lex[i] / maxLex
    const vec = emb?.chunks[`${c.id}@v${c.meta.version}`]
    const sem = queryVec && vec ? Math.max(0, cosine(queryVec, vec)) : null
    const base = sem !== null ? 0.55 * lexNorm + 0.45 * sem : lexNorm
    return { c, score: base + AUTHORITY_BOOST[c.meta.evidenceStrength], hasSignal: lex[i] > 0 || sem !== null }
  })

  const top = scored
    .filter(s => s.hasSignal || pool.length <= limit)
    .sort((a, b) => b.score - a.score || a.c.id.localeCompare(b.c.id))   // stable tiebreak → determinism
    .slice(0, limit)

  const maxScore = top[0]?.score || 1
  return {
    guidance: top.map(({ c, score }) => toGuidance(ix, c, score / maxScore)),
    kbVersion: ix.version,
  }
}

function toGuidance(ix: Index, c: KnowledgeChunk, retrievalScore: number): RetrievedGuidance {
  const doc = ix.docById.get(c.docId)
  return {
    text: c.text,
    org: c.meta.org,
    title: doc?.title ?? c.meta.org,
    url: doc?.url ?? '',
    publishedDate: c.meta.publishedDate,
    evidenceStrength: c.meta.evidenceStrength,
    chunkId: c.id,
    chunkVersion: c.meta.version,
    retrievalScore: Math.round(retrievalScore * 100) / 100,
  }
}

/** Used by the update detector: which chunks belong to a doc */
export function chunksForDoc(docId: string): KnowledgeChunk[] {
  return allChunks().filter(c => c.docId === docId)
}
